//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeto_FILA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filas
    {
        public int FilaID { get; set; }
        public int Situacao { get; set; }
        public int ClienteID { get; set; }
        public int FuncionarioID { get; set; }
        public int ServicoID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Funcionarios Funcionarios { get; set; }
        public virtual Servicoes Servicoes { get; set; }
    }
}
